-- This file is generated by program!
-- Don't change it manaully.
-- Author: chuxiang9007@163.com  NormanYang
-- Source file: 策划数值配置/英雄表.xlsx
-- Created at: Thu Dec 17 08:57:14 2015


local data = {}

data[1000] = { id = 1000,  name = "house",  use_money = 1000,  use_food = 2.33,  is_init = true,  defense = 100,  args1 = {1,2,3},  args2 = {1.23,2,3.23},  args3 = {"sdf","23e","s"},  args4 = {true,false,true}}
data[1001] = { id = 1001,  name = "你好吗？",  use_money = 123,  use_food = 336.2,  is_init = true,  defense = 0,  args1 = {1,2,3},  args2 = {1,2.3445,3},  args3 = {"你好","你在哪"},  args4 = {true,false}}
data[1002] = { id = 1002,  name = "",  use_money = 456,  use_food = 222.33665,  is_init = false,  defense = 130,  args1 = {3,2,5},  args2 = {3,2,2.5},  args3 = {"我在这里啊","你在那","呢"},  args4 = {false,true}}
data[1003] = { id = 1003,  name = "farm",  use_money = 100,  use_food = 220.0,  is_init = false,  defense = 200,  args1 = {2,3},  args2 = {200.3,3,234.23},  args3 = {"df","ssd","dd","dd"},  args4 = {}}
data[1004] = { id = 1004,  name = "house5",  use_money = 0,  use_food = 22.1,  is_init = false,  defense = 234,  args1 = {3,6,6,7},  args2 = {3,6.3,6,7},  args3 = {"ss","d","d","d"},  args4 = {true,true}}
data[1005] = { id = 1005,  name = "horse3",  use_money = 200,  use_food = 0,  is_init = false,  defense = 333,  args1 = {},  args2 = {},  args3 = {"2e","w","e","we"},  args4 = {false,false,false,false}}

return data
